import {Component, OnInit, ViewChild} from '@angular/core';
import {MatPaginator} from '@angular/material/paginator';
import {MatTableDataSource} from '@angular/material/table';
import { from } from 'rxjs';


@Component({
  selector: 'app-departments',
  templateUrl: './departments.component.html',
  styleUrls: ['./departments.component.scss']
})
export class DepartmentsComponent implements OnInit {

  displayedColumns: string[] = ['id','enable','priority','department','start_working_time',
  'end_working_time', 'nwd_table_id','dialplan_context','queue','query_method','url_id',
  'call_more', 'retry_time']
  dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

  @ViewChild(MatPaginator, {static: true}) paginator: MatPaginator;

  ngOnInit() {
    this.dataSource.paginator = this.paginator;
  }
}

export interface PeriodicElement {
  id: number;
  enable: number;
  priority: number;
  department: string;
  start_working_time: string;
  end_working_time: string;
  nwd_table_id: number;
  dialplan_context: string;
  queue: string;
  query_method: string;
  url_id: number;
  call_more: number;
  retry_time: number;
}

const ELEMENT_DATA: PeriodicElement[] = [
  {
    "id": 1,
    "enable": 1,
    "priority": 7,
    "department": "qm-pcs",
    "start_working_time": "8:00:00",
    "end_working_time": "17:50:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 3,
    "call_more": 1,
    "retry_time": 180,
  },
  {
    "id": 2,
    "enable": 1,
    "priority": 0,
    "department": "mobile",
    "start_working_time": "0:00:00",
    "end_working_time": "24:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-test-start",
    "queue": "research",
    "query_method": "QS4",
    "url_id": 1,
    "call_more": 1,
    "retry_time": 180,
  },
  {
    "id": 3,
    "enable": 1,
    "priority": 0,
    "department": "test",
    "start_working_time": "0:00:00",
    "end_working_time": "24:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-test-start",
    "queue": "research",
    "query_method": "QS1",
    "url_id": 1,
    "call_more": 1,
    "retry_time": 5,
  },
  {
    "id": 4,
    "enable": 1,
    "priority": 4,
    "department": "qm-cancel",
    "start_working_time": "8:00:00",
    "end_working_time": "17:30:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 4,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 5,
    "enable": 1,
    "priority": 1,
    "department": "qm-satisfaction",
    "start_working_time": "8:00:00",
    "end_working_time": "17:31:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 5,
    "call_more": 3,
    "retry_time": 180,
  },
  {
    "id": 6,
    "enable": 1,
    "priority": 5,
    "department": "qm-changeservice",
    "start_working_time": "8:00:00",
    "end_working_time": "17:35:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 6,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 7,
    "enable": 1,
    "priority": 6,
    "department": "qm-changeline",
    "start_working_time": "8:00:00",
    "end_working_time": "17:35:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 7,
    "call_more": 1,
    "retry_time": 180,
  },
  {
    "id": 8,
    "enable": 1,
    "priority": 3,
    "department": "qm-installation",
    "start_working_time": "8:00:00",
    "end_working_time": "17:35:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 8,
    "call_more": 1,
    "retry_time": 180,
  },
  {
    "id": 9,
    "enable": 1,
    "priority": 8,
    "department": "qm-delivery",
    "start_working_time": "8:00:00",
    "end_working_time": "17:35:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 9,
    "call_more": 1,
    "retry_time": 180,
  },
  {
    "id": 10,
    "enable": 1,
    "priority": 0,
    "department": "rating-care-outbound",
    "start_working_time": "0:00:00",
    "end_working_time": "24:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-rating-start",
    "queue": "rating",
    "query_method": "RS1",
    "url_id": 1,
    "call_more": 10,
    "retry_time": 20,
  },
  {
    "id": 11,
    "enable": 1,
    "priority": 0,
    "department": "cts-callback",
    "start_working_time": "0:00:00",
    "end_working_time": "24:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmcallback-start",
    "queue": "ctscallback",
    "query_method": "RS1",
    "url_id": 1,
    "call_more": 10,
    "retry_time": 5,
  },
  {
    "id": 12,
    "enable": 1,
    "priority": 0,
    "department": "rating-care-eco",
    "start_working_time": "8:00:00",
    "end_working_time": "24:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-rating-start",
    "queue": "rating",
    "query_method": "RS1",
    "url_id": 1,
    "call_more": 10,
    "retry_time": 20,
  },
  {
    "id": 13,
    "enable": 1,
    "priority": 0,
    "department": "rating-cs-eco",
    "start_working_time": "8:00:00",
    "end_working_time": "24:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-rating-start",
    "queue": "rating",
    "query_method": "RS1",
    "url_id": 1,
    "call_more": 10,
    "retry_time": 20,
  },
  {
    "id": 15,
    "enable": 1,
    "priority": 0,
    "department": "sales-dcdebt",
    "start_working_time": "8:00:00",
    "end_working_time": "16:23:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmsales1-start",
    "queue": "cmsales1",
    "query_method": "SS2",
    "url_id": 1,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 16,
    "enable": 1,
    "priority": 0,
    "department": "sales-dctraffic",
    "start_working_time": "8:00:00",
    "end_working_time": "16:23:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmsales1-start",
    "queue": "cmsales1",
    "query_method": "SS2",
    "url_id": 2,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 17,
    "enable": 1,
    "priority": 0,
    "department": "qm-oss",
    "start_working_time": "8:00:00",
    "end_working_time": "17:31:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm2-start",
    "queue": "cmqm2",
    "query_method": "QS1",
    "url_id": 1,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 18,
    "enable": 1,
    "priority": 0,
    "department": "qm-province",
    "start_working_time": "8:00:00",
    "end_working_time": "17:35:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm2-start",
    "queue": "cmqm2",
    "query_method": "QS1",
    "url_id": 2,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 19,
    "enable": 0,
    "priority": 0,
    "department": "sales-mobile",
    "start_working_time": "8:00:00",
    "end_working_time": "16:23:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmsales2-start",
    "queue": "cmsales2",
    "query_method": "SS2",
    "url_id": 2,
    "call_more": 1,
    "retry_time": 180,
  },
  {
    "id": 20,
    "enable": 1,
    "priority": 0,
    "department": "sales-fttc",
    "start_working_time": "9:00:00",
    "end_working_time": "22:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmsales3-start",
    "queue": "cmsales3",
    "query_method": "SS2",
    "url_id": 2,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 21,
    "enable": 1,
    "priority": 2,
    "department": "qm-namava",
    "start_working_time": "8:00:00",
    "end_working_time": "17:35:00",
    "nwd_table_id": 1,
    "dialplan_context": "calling-machine-cmqm1-start",
    "queue": "cmqm1",
    "query_method": "QS1",
    "url_id": 10,
    "call_more": 1,
    "retry_time": 180,
  },
  {
    "id": 22,
    "enable": 1,
    "priority": 2,
    "department": "over-dcdebtoss",
    "start_working_time": "8:30:00",
    "end_working_time": "22:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmsales2-start",
    "queue": "cmsales2",
    "query_method": "SS2",
    "url_id": 1,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 23,
    "enable": 1,
    "priority": 3,
    "department": "over-dcdebtposs",
    "start_working_time": "8:30:00",
    "end_working_time": "22:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmsales2-start",
    "queue": "cmsales2",
    "query_method": "SS2",
    "url_id": 2,
    "call_more": 2,
    "retry_time": 180,
  },
  {
    "id": 24,
    "enable": 1,
    "priority": 1,
    "department": "over-dcdebtposs-h",
    "start_working_time": "8:30:00",
    "end_working_time": "21:00:00",
    "nwd_table_id": 0,
    "dialplan_context": "calling-machine-cmsales2-start",
    "queue": "cmsales2",
    "query_method": "SS2",
    "url_id": 2,
    "call_more": 2,
    "retry_time": 180,
  }
];
